[build]
  publish = "_site"
  command = "yarn run build"
  NODE_ENV = "10.15.3"

[dev]
  command = "yarn run start"


[[headers]]
  for = "assets/images/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/images/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/images/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/images/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/images/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "assets/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"


[[redirects]]
  from = "/images/tiny/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat?nf_resize=fit&w=20"
  status = 302

[[redirects]]
  from = "/images/small/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat?nf_resize=fit&w=500"
  status = 302

[[redirects]]
  from = "/images/medium/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat?nf_resize=fit&w=600"
  status = 302

[[redirects]]
  from = "/images/large/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat?nf_resize=fit&w=700"
  status = 302

[[redirects]]
  from = "/images/original/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat"
  status = 302