[build]
  publish = "_site"
  command = "eleventy"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"